"""add_document_metadata

Revision ID: a03a9e902522
Revises: 18d79a51168d
Create Date: 2026-05-09 16:28:38.801312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a03a9e902522'
down_revision: Union[str, None] = '18d79a51168d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('language', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('academic_year', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('term', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'term')
    op.drop_column('documents', 'academic_year')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
