import { useState, useEffect, useCallback } from 'react';
import Layout from '../../components/Layout';
import { adminAPI, lessonPlanAPI, questionPaperAPI } from '../../services/api';
import {
  FileText, ClipboardList, Loader2, X, Search, Filter, CheckCircle, XCircle,
  RotateCcw, Archive, ArchiveRestore, Trash2, Download, History, Wand2,
  ChevronLeft, ChevronRight, Save, AlertCircle, Clock, User as UserIcon,
} from 'lucide-react';

// The two content types the admin oversees. `key` matches the API path segment.
const TABS = [
  { key: 'lesson-plans',    label: 'Lesson Plans',    icon: ClipboardList },
  { key: 'question-papers', label: 'Question Papers', icon: FileText },
];

const STATUS_BADGE = {
  pending:  { cls: 'badge-yellow', label: 'Pending review' },
  approved: { cls: 'badge-green',  label: 'Approved' },
  rejected: { cls: 'badge-red',    label: 'Rejected' },
};

const ACTION_STYLE = {
  created:     { cls: 'badge-blue',   label: 'Created' },
  updated:     { cls: 'badge-purple', label: 'Edited' },
  regenerated: { cls: 'badge-purple', label: 'Regenerated by AI' },
  approved:    { cls: 'badge-green',  label: 'Approved' },
  rejected:    { cls: 'badge-red',    label: 'Rejected' },
  published:   { cls: 'badge-green',  label: 'Published' },
  unpublished: { cls: 'badge-gray',   label: 'Unpublished' },
  archived:    { cls: 'badge-gray',   label: 'Archived' },
  restored:    { cls: 'badge-blue',   label: 'Restored' },
  deleted:     { cls: 'badge-red',    label: 'Deleted' },
};

// Grades 1-2 papers carry an internal source per question, for audit only.
// Mirrors SOURCE_LABELS in backend-python/services/primary_papers.py.
const SOURCE_LABELS = {
  lesson_planner_classwork: 'Lesson Planner — Classwork',
  bookwork: 'Bookwork',
  end_of_chapter_exercise: 'End-of-Chapter Exercise',
  end_of_book_exercise: 'End-of-Book Exercise',
};

const EMPTY_FILTERS = {
  teacher_id: '', subject: '', class_name: '', section: '',
  academic_session: '', review_status: '', record_type: '',
  is_published: '', is_archived: '', date_from: '', date_to: '', q: '',
};

const PAGE_SIZE = 25;

const fmtDate = (iso) => (iso ? new Date(iso).toLocaleDateString() : '—');
const fmtDateTime = (iso) => (iso ? new Date(iso).toLocaleString() : '—');

export default function ContentOversight() {
  const [tab, setTab] = useState('lesson-plans');
  const [items, setItems] = useState([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState(EMPTY_FILTERS);
  const [options, setOptions] = useState({ teachers: [], subjects: [], classes: [], sections: [], sessions: [], plan_types: [], paper_types: [] });
  const [summary, setSummary] = useState(null);
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const flash = (msg) => { setSuccess(msg); setTimeout(() => setSuccess(''), 3500); };

  const load = useCallback(async () => {
    setLoading(true);
    try {
      // Blank filter values mean "no filter" — don't send them.
      const params = { page, page_size: PAGE_SIZE };
      Object.entries(filters).forEach(([k, v]) => { if (v !== '') params[k] = v; });
      const { data } = await adminAPI.listContent(tab, params);
      setItems(data.items);
      setTotal(data.total);
    } catch (e) {
      setError(e.response?.data?.detail || 'Failed to load records');
    } finally {
      setLoading(false);
    }
  }, [tab, page, filters]);

  useEffect(() => { load(); }, [load]);

  useEffect(() => {
    adminAPI.getContentFilters().then(({ data }) => setOptions(data)).catch(() => {});
    adminAPI.getContentSummary().then(({ data }) => setSummary(data)).catch(() => {});
  }, []);

  const refreshSummary = () => adminAPI.getContentSummary().then(({ data }) => setSummary(data)).catch(() => {});

  const setF = (k, v) => { setPage(1); setFilters((f) => ({ ...f, [k]: v })); };
  const clearFilters = () => { setPage(1); setFilters(EMPTY_FILTERS); };
  const activeFilterCount = Object.values(filters).filter((v) => v !== '').length;

  const openDetail = async (id) => {
    setError('');
    try {
      const { data } = await adminAPI.getContent(tab, id);
      setDetail(data);
    } catch (e) {
      setError(e.response?.data?.detail || 'Failed to open record');
    }
  };

  // A record changed: refresh the row in place, the detail pane and the counts.
  const applyUpdate = (updated) => {
    setItems((prev) => prev.map((it) => (it.id === updated.id ? { ...it, ...updated } : it)));
    setDetail((d) => (d && d.id === updated.id ? { ...d, ...updated } : d));
    refreshSummary();
  };

  const stats = summary?.[tab];
  const typeOptions = tab === 'lesson-plans' ? options.plan_types : options.paper_types;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <Layout>
      <div className="space-y-5">
        <div>
          <h1 className="text-2xl font-bold text-ink">Content Oversight</h1>
          <p className="text-sm text-muted mt-1">
            Every lesson plan and examination paper created by teachers, with full review history.
          </p>
        </div>

        {error && (
          <div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm flex items-start gap-2 border border-red-200">
            <AlertCircle size={16} className="mt-0.5 shrink-0" /> <span className="flex-1">{error}</span>
            <button onClick={() => setError('')}><X size={14} /></button>
          </div>
        )}
        {success && (
          <div className="p-3 rounded-lg bg-green-50 text-green-700 text-sm flex items-center gap-2 border border-green-200">
            <CheckCircle size={16} /> {success}
          </div>
        )}

        {/* Tabs */}
        <div className="flex gap-2">
          {TABS.map(({ key, label, icon: Icon }) => (
            <button
              key={key}
              onClick={() => { setTab(key); setPage(1); }}
              className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${
                tab === key ? 'bg-blue-600 text-white' : 'bg-surface-2 text-muted hover:text-ink'
              }`}
            >
              <Icon size={15} /> {label}
              {summary?.[key] && <span className="text-xs opacity-80">({summary[key].total})</span>}
            </button>
          ))}
        </div>

        {/* Status summary */}
        {stats && (
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            {[
              ['Total', stats.total, 'text-ink'],
              ['Pending review', stats.pending, 'text-yellow-600'],
              ['Approved', stats.approved, 'text-green-600'],
              ['Rejected', stats.rejected, 'text-red-600'],
              ['Published', stats.published, 'text-blue-600'],
            ].map(([label, value, cls]) => (
              <div key={label} className="card p-3">
                <p className="text-xs text-muted">{label}</p>
                <p className={`text-xl font-bold ${cls}`}>{value}</p>
              </div>
            ))}
          </div>
        )}

        {/* Filters */}
        <div className="card p-4 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm font-semibold text-ink flex items-center gap-2">
              <Filter size={14} /> Filters
              {activeFilterCount > 0 && <span className="badge-blue">{activeFilterCount} active</span>}
            </span>
            {activeFilterCount > 0 && (
              <button onClick={clearFilters} className="text-xs text-muted hover:text-ink">Clear all</button>
            )}
          </div>

          <div className="relative">
            <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-faint" />
            <input
              value={filters.q}
              onChange={(e) => setF('q', e.target.value)}
              placeholder="Search by title, subject or class"
              className="input-field pl-9"
            />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <Select label="Teacher" value={filters.teacher_id} onChange={(v) => setF('teacher_id', v)}
              options={options.teachers.map((t) => ({ value: t.id, label: t.name }))} />
            <Select label="Subject" value={filters.subject} onChange={(v) => setF('subject', v)}
              options={options.subjects.map((s) => ({ value: s, label: s }))} />
            <Select label="Class / Grade" value={filters.class_name} onChange={(v) => setF('class_name', v)}
              options={options.classes.map((c) => ({ value: c, label: c }))} />
            <Select label="Section" value={filters.section} onChange={(v) => setF('section', v)}
              options={options.sections.map((s) => ({ value: s, label: s }))} />
            <Select label="Academic session" value={filters.academic_session} onChange={(v) => setF('academic_session', v)}
              options={options.sessions.map((s) => ({ value: s, label: s }))} />
            <Select label={tab === 'lesson-plans' ? 'Plan type' : 'Paper type'} value={filters.record_type}
              onChange={(v) => setF('record_type', v)}
              options={(typeOptions || []).map((t) => ({ value: t, label: t.replace(/_/g, ' ') }))} />
            <Select label="Review status" value={filters.review_status} onChange={(v) => setF('review_status', v)}
              options={[
                { value: 'pending', label: 'Pending review' },
                { value: 'approved', label: 'Approved' },
                { value: 'rejected', label: 'Rejected' },
              ]} />
            <Select label="Visibility" value={filters.is_published} onChange={(v) => setF('is_published', v)}
              options={[{ value: 'true', label: 'Published' }, { value: 'false', label: 'Unpublished' }]} />
            <div>
              <label className="block text-xs font-medium text-muted mb-1">Created from</label>
              <input type="date" value={filters.date_from} onChange={(e) => setF('date_from', e.target.value)} className="input-field" />
            </div>
            <div>
              <label className="block text-xs font-medium text-muted mb-1">Created to</label>
              <input type="date" value={filters.date_to} onChange={(e) => setF('date_to', e.target.value)} className="input-field" />
            </div>
            <Select label="Archived" value={filters.is_archived} onChange={(v) => setF('is_archived', v)}
              options={[{ value: 'true', label: 'Archived only' }, { value: 'false', label: 'Live only' }]}
              placeholder="Live only" />
          </div>
        </div>

        {/* Records */}
        <div className="card overflow-hidden">
          {loading ? (
            <div className="p-10 text-center text-muted"><Loader2 className="animate-spin mx-auto" /></div>
          ) : items.length === 0 ? (
            <div className="p-10 text-center text-muted text-sm">
              No records match these filters.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-surface-2 text-muted">
                  <tr>
                    {['Title', 'Teacher', 'Class', 'Subject', 'Created', 'Status', ''].map((h) => (
                      <th key={h} className="text-left font-medium px-4 py-2.5 whitespace-nowrap">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {items.map((it) => {
                    const badge = STATUS_BADGE[it.review_status] || STATUS_BADGE.pending;
                    return (
                      <tr key={it.id} className="border-t border-line hover:bg-surface-2/60">
                        <td className="px-4 py-2.5">
                          <button onClick={() => openDetail(it.id)} className="text-left font-medium text-ink hover:text-blue-600">
                            {it.title}
                          </button>
                          <div className="flex items-center gap-1.5 mt-1">
                            {it.is_published && <span className="badge-blue">Published</span>}
                            {it.is_archived && <span className="badge-gray">Archived</span>}
                            <span className="text-xs text-faint">v{it.version}</span>
                          </div>
                        </td>
                        <td className="px-4 py-2.5 text-muted whitespace-nowrap">{it.teacher_name || '—'}</td>
                        <td className="px-4 py-2.5 text-muted whitespace-nowrap">
                          {it.class_name}{it.section ? ` – ${it.section}` : ''}
                        </td>
                        <td className="px-4 py-2.5 text-muted whitespace-nowrap">{it.subject}</td>
                        <td className="px-4 py-2.5 text-muted whitespace-nowrap">{fmtDate(it.created_at)}</td>
                        <td className="px-4 py-2.5"><span className={badge.cls}>{badge.label}</span></td>
                        <td className="px-4 py-2.5 text-right">
                          <button onClick={() => openDetail(it.id)} className="btn-secondary text-xs py-1 px-2.5">Review</button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}

          {total > PAGE_SIZE && (
            <div className="flex items-center justify-between px-4 py-3 border-t border-line text-sm">
              <span className="text-muted">
                {(page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, total)} of {total}
              </span>
              <div className="flex items-center gap-2">
                <button disabled={page <= 1} onClick={() => setPage((p) => p - 1)}
                  className="btn-secondary p-1.5 disabled:opacity-40"><ChevronLeft size={15} /></button>
                <span className="text-muted">{page} / {totalPages}</span>
                <button disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}
                  className="btn-secondary p-1.5 disabled:opacity-40"><ChevronRight size={15} /></button>
              </div>
            </div>
          )}
        </div>
      </div>

      {detail && (
        <DetailDrawer
          type={tab}
          record={detail}
          onClose={() => setDetail(null)}
          onUpdated={applyUpdate}
          onDeleted={(id) => {
            setItems((prev) => prev.filter((it) => it.id !== id));
            setDetail(null);
            refreshSummary();
            flash('Record deleted');
          }}
          onFlash={flash}
          onError={setError}
        />
      )}
    </Layout>
  );
}

function Select({ label, value, onChange, options, placeholder = 'Any' }) {
  return (
    <div>
      <label className="block text-xs font-medium text-muted mb-1">{label}</label>
      <select value={value} onChange={(e) => onChange(e.target.value)} className="input-field">
        <option value="">{placeholder}</option>
        {options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
      </select>
    </div>
  );
}

// ─── Detail / review drawer ───────────────────────────────────────────────────

function DetailDrawer({ type, record, onClose, onUpdated, onDeleted, onFlash, onError }) {
  const isPlan = type === 'lesson-plans';
  const [busy, setBusy] = useState('');
  const [note, setNote] = useState('');
  const [title, setTitle] = useState(record.title);
  const [view, setView] = useState('content');

  useEffect(() => { setTitle(record.title); setNote(''); }, [record.id]);

  const run = async (key, fn, successMsg) => {
    setBusy(key);
    onError('');
    try {
      const { data } = await fn();
      if (data?.id) onUpdated(data);
      if (successMsg) onFlash(successMsg);
      return data;
    } catch (e) {
      onError(e.response?.data?.detail || 'Action failed');
    } finally {
      setBusy('');
    }
  };

  const review = (decision) => {
    if (decision === 'rejected' && !note.trim()) {
      onError('Add a note explaining what needs to change before rejecting.');
      return;
    }
    return run(decision, () => adminAPI.reviewContent(type, record.id, { decision, note: note.trim() || null }),
      decision === 'approved' ? 'Approved' : decision === 'rejected' ? 'Rejected' : 'Re-opened for review');
  };

  const saveTitle = () => run('title', () => adminAPI.editContent(type, record.id, { title, note: 'Title edited by administrator' }), 'Saved');

  const regenerate = () => {
    if (!window.confirm('Regenerate this record with the AI? The current version is kept in the history.')) return;
    return run('regen', () => adminAPI.regenerateContent(type, record.id), 'Regenerated');
  };

  const toggleArchive = () => run('archive',
    () => adminAPI.archiveContent(type, record.id, { archived: !record.is_archived }),
    record.is_archived ? 'Restored' : 'Archived');

  const remove = async () => {
    if (!window.confirm('Permanently delete this record? Its history is kept for audit.')) return;
    setBusy('delete');
    try {
      await adminAPI.deleteContent(type, record.id);
      onDeleted(record.id);
    } catch (e) {
      onError(e.response?.data?.detail || 'Delete failed');
    } finally {
      setBusy('');
    }
  };

  const download = async (fmt) => {
    setBusy(fmt);
    try {
      const api = isPlan ? lessonPlanAPI : questionPaperAPI;
      const { data } = fmt === 'docx' ? await api.downloadDocx(record.id) : await api.downloadPdf(record.id);
      const safe = (record.title || 'document').replace(/[^a-z0-9]/gi, '_');
      const url = window.URL.createObjectURL(new Blob([data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${safe}.${fmt}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (e) {
      onError('Download failed');
    } finally {
      setBusy('');
    }
  };

  const badge = STATUS_BADGE[record.review_status] || STATUS_BADGE.pending;
  const spin = (k) => busy === k && <Loader2 size={14} className="animate-spin" />;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-start justify-center p-4 overflow-y-auto">
      <div className="bg-surface rounded-2xl shadow-xl w-full max-w-4xl my-4">
        <div className="p-5 border-b border-line flex items-start justify-between gap-4">
          <div className="min-w-0">
            <h2 className="font-bold text-ink truncate">{record.title}</h2>
            <p className="text-sm text-muted mt-0.5">
              {record.subject} • {record.class_name}{record.section ? ` – ${record.section}` : ''}
              {record.academic_session ? ` • ${record.academic_session}` : ''} • v{record.version}
            </p>
            <div className="flex items-center gap-1.5 mt-2 flex-wrap">
              <span className={badge.cls}>{badge.label}</span>
              {record.is_published && <span className="badge-blue">Published</span>}
              {record.is_archived && <span className="badge-gray">Archived</span>}
            </div>
          </div>
          <button onClick={onClose} className="text-faint hover:text-muted shrink-0"><X size={20} /></button>
        </div>

        {/* Audit summary */}
        <div className="px-5 py-3 border-b border-line grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
          <Fact icon={UserIcon} label="Created by" value={record.teacher_name || '—'} sub={fmtDateTime(record.created_at)} />
          <Fact icon={Clock} label="Last modified" value={record.updated_by_name || record.teacher_name || '—'} sub={fmtDateTime(record.updated_at)} />
          <Fact icon={CheckCircle} label="Reviewed by" value={record.reviewed_by_name || 'Not reviewed'} sub={fmtDateTime(record.reviewed_at)} />
          <Fact icon={History} label="Versions" value={`${record.revisions?.length || 0} entries`} sub={`Currently v${record.version}`} />
        </div>

        {record.review_note && (
          <div className="mx-5 mt-3 p-3 rounded-lg bg-surface-2 text-sm text-muted">
            <span className="font-medium text-ink">Review note: </span>{record.review_note}
          </div>
        )}

        <div className="px-5 pt-3 flex gap-2">
          {['content', 'history'].map((v) => (
            <button key={v} onClick={() => setView(v)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium ${view === v ? 'bg-blue-600 text-white' : 'bg-surface-2 text-muted hover:text-ink'}`}>
              {v === 'content' ? 'Content' : 'Version history'}
            </button>
          ))}
        </div>

        <div className="p-5 max-h-[45vh] overflow-y-auto">
          {view === 'content'
            ? (isPlan ? <PlanContent plan={record} /> : <PaperContent paper={record} />)
            : <RevisionList revisions={record.revisions || []} />}
        </div>

        {/* Actions */}
        <div className="p-5 border-t border-line space-y-3">
          <div className="flex items-end gap-2">
            <div className="flex-1">
              <label className="block text-xs font-medium text-muted mb-1">Title</label>
              <input value={title} onChange={(e) => setTitle(e.target.value)} className="input-field" />
            </div>
            <button onClick={saveTitle} disabled={busy || title === record.title}
              className="btn-secondary flex items-center gap-1.5 text-sm disabled:opacity-40">
              {spin('title') || <Save size={14} />} Save
            </button>
          </div>

          <div>
            <label className="block text-xs font-medium text-muted mb-1">
              Review note {record.review_status !== 'rejected' && <span className="text-faint">(required to reject)</span>}
            </label>
            <textarea value={note} onChange={(e) => setNote(e.target.value)} rows={2}
              placeholder="Feedback for the teacher…" className="input-field resize-none" />
          </div>

          <div className="flex flex-wrap gap-2">
            <button onClick={() => review('approved')} disabled={!!busy}
              className="btn-primary flex items-center gap-1.5 text-sm">
              {spin('approved') || <CheckCircle size={15} />} Approve
            </button>
            <button onClick={() => review('rejected')} disabled={!!busy}
              className="btn-danger flex items-center gap-1.5 text-sm">
              {spin('rejected') || <XCircle size={15} />} Reject
            </button>
            {record.review_status !== 'pending' && (
              <button onClick={() => review('pending')} disabled={!!busy}
                className="btn-secondary flex items-center gap-1.5 text-sm">
                {spin('pending') || <RotateCcw size={15} />} Re-open
              </button>
            )}
            <button onClick={regenerate} disabled={!!busy}
              className="btn-secondary flex items-center gap-1.5 text-sm"
              title="Re-run the AI using this record's original inputs">
              {spin('regen') || <Wand2 size={15} />} Regenerate
            </button>
            <button onClick={() => download('pdf')} disabled={!!busy}
              className="btn-secondary flex items-center gap-1.5 text-sm">
              {spin('pdf') || <Download size={15} />} PDF
            </button>
            {isPlan && (
              <button onClick={() => download('docx')} disabled={!!busy}
                className="btn-secondary flex items-center gap-1.5 text-sm">
                {spin('docx') || <Download size={15} />} Word
              </button>
            )}
            <button onClick={toggleArchive} disabled={!!busy}
              className="btn-secondary flex items-center gap-1.5 text-sm">
              {spin('archive') || (record.is_archived ? <ArchiveRestore size={15} /> : <Archive size={15} />)}
              {record.is_archived ? 'Restore' : 'Archive'}
            </button>
            <button onClick={remove} disabled={!!busy}
              className="btn-danger flex items-center gap-1.5 text-sm ml-auto">
              {spin('delete') || <Trash2 size={15} />} Delete
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function Fact({ icon: Icon, label, value, sub }) {
  return (
    <div>
      <p className="text-muted flex items-center gap-1"><Icon size={12} /> {label}</p>
      <p className="text-ink font-medium mt-0.5 truncate">{value}</p>
      <p className="text-faint">{sub}</p>
    </div>
  );
}

function RevisionList({ revisions }) {
  if (revisions.length === 0) {
    return <p className="text-sm text-muted text-center py-6">No history recorded yet.</p>;
  }
  return (
    <ol className="space-y-3">
      {revisions.map((r) => {
        const style = ACTION_STYLE[r.action] || { cls: 'badge-gray', label: r.action };
        return (
          <li key={r.id} className="flex gap-3">
            <div className="w-1 rounded bg-line shrink-0" />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className={style.cls}>{style.label}</span>
                <span className="text-xs text-faint">v{r.version}</span>
                {r.ai_generated && <span className="badge-purple">AI</span>}
              </div>
              <p className="text-sm text-ink mt-1">
                {r.actor_name || 'Unknown'}{r.actor_role ? ` (${r.actor_role})` : ''}
                <span className="text-faint"> — {fmtDateTime(r.created_at)}</span>
              </p>
              {r.note && <p className="text-sm text-muted mt-0.5">{r.note}</p>}
            </div>
          </li>
        );
      })}
    </ol>
  );
}

function PlanContent({ plan }) {
  const data = plan.plan_data || {};
  const lessons = data.lessons || [];
  const outcomes = data.learning_outcomes || [];
  return (
    <div className="space-y-3 text-sm">
      {outcomes.length > 0 && (
        <Block title="Students Learning Outcomes">
          <ol className="list-decimal ml-5 space-y-1 text-muted">
            {outcomes.map((o, i) => <li key={i}>{o}</li>)}
          </ol>
        </Block>
      )}
      {data.starter_activity && <Block title="Starter Activity"><p className="text-muted">{data.starter_activity}</p></Block>}
      {(data.weekly_plan || []).length > 0 && (
        <Block title="Week-wise Planning">
          <ul className="space-y-1 text-muted">
            {data.weekly_plan.map((d, i) => (
              <li key={i}><span className="font-medium text-ink">{d.day}:</span> {d.classwork}</li>
            ))}
          </ul>
        </Block>
      )}
      {lessons.length > 0 && (
        <Block title={`Schedule (${lessons.length} lessons)`}>
          <ul className="space-y-1 text-muted">
            {lessons.slice(0, 12).map((l, i) => (
              <li key={i}>
                <span className="font-medium text-ink">{l.week ? `Week ${l.week}` : `Lesson ${i + 1}`}:</span>{' '}
                {l.topic || l.chapter || '—'}
              </li>
            ))}
            {lessons.length > 12 && <li className="text-faint">…and {lessons.length - 12} more — download the PDF for the full plan.</li>}
          </ul>
        </Block>
      )}
      {outcomes.length === 0 && lessons.length === 0 && !data.starter_activity && (
        <p className="text-muted">No structured content stored. Download the PDF to review this plan.</p>
      )}
    </div>
  );
}

function PaperContent({ paper }) {
  const questions = paper.questions || [];
  const answers = Object.fromEntries((paper.answer_key || []).map((a) => [a.number, a.correct_answer]));
  if (questions.length === 0) return <p className="text-sm text-muted">No questions stored.</p>;

  let lastSection = null;
  return (
    <div className="space-y-3 text-sm">
      <p className="text-muted">
        {questions.length} questions • {paper.total_marks} marks • {paper.duration_minutes} min
      </p>
      {questions.map((q, i) => {
        const header = q.section !== lastSection ? q.section : null;
        lastSection = q.section;
        return (
          <div key={i}>
            {header && <p className="font-semibold text-ink mt-3 mb-1">{header}</p>}
            <div className="border border-line rounded-lg p-3">
              <p className="text-ink">
                <span className="font-medium">Q{q.number}.</span> {q.question}
                <span className="text-xs text-faint ml-2">({q.marks} marks)</span>
              </p>
              {(q.options || []).length > 0 && (
                <div className="mt-1.5 space-y-0.5">
                  {q.options.map((o, j) => <p key={j} className="text-xs text-muted ml-3">{o}</p>)}
                </div>
              )}
              {answers[q.number] && (
                <p className="text-xs text-green-700 mt-1.5">
                  <span className="font-medium">Answer:</span> {answers[q.number]}
                </p>
              )}
              {q.source && (
                <div className="mt-2 pt-2 border-t border-line text-xs text-muted">
                  <span className="badge-purple">{SOURCE_LABELS[q.source.type] || 'Unverified source'}</span>
                  <span className="ml-2">{q.source.reference}</span>
                  {q.source.planner_title && <span className="text-faint"> — {q.source.planner_title}</span>}
                  {q.source.taught_confirmation && (
                    <p className="text-faint mt-0.5">Taught: {q.source.taught_confirmation}</p>
                  )}
                </div>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function Block({ title, children }) {
  return (
    <div>
      <p className="font-semibold text-ink mb-1">{title}</p>
      {children}
    </div>
  );
}
